include: package:very_good_analysis/analysis_options.6.0.0.yaml
analyzer:
  exclude:
    - lib/gen/*
linter:
  rules:
    public_member_api_docs: false
    avoid_redundant_argument_values: false
    lines_longer_than_80_chars: false
    prefer_int_literals: false
